<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?php echo $this->__('Proceed to Checkout') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
    <br/>
    <?php if ($this->helper('OneID')->isBrowserOneIdSupported()) :?>
        <button type="button" style="margin-top: 5px;" title="<?php echo $this->__('Check out with OneID') ?>" class="oneid-only button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>?autoFill=true';"><img id="oneid_checkout_button" src="<?php echo $this->helper('OneID')->getEndPoint()?>/images/oneid_checkout@2x.png" style="width:136px; height:24px;"></button>
        <script type="text/javascript">
            OneIdExtern.registerApiReadyFunction(function(){
                OneIdUtil.imageHighlight("#oneid_checkout_button");
            });
        </script>
    <?php endif ?>
<?php endif?>
