<script type="text/javascript">
//<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
//]]>
</script>
<form action="" id="co-payment-form">
    <fieldset>
        <?php echo $this->getChildChildHtml('methods_additional', '', true, true) ?>
        <?php echo $this->getChildHtml('methods') ?>
        <input id='oneIDPurchaseAuthData' type="hidden" name="oneIDPurchaseAuthData" />
    </fieldset>
  <script>
    OneIdExtern.registerApiReadyFunction(function(){
        OneId.accuFillButton(OneId.$(".oneid-formfill-payment"), paymentPostData, "", function(completed){
          if (!completed && OneId.automateFormFill){
            recoverFromFailedOneidCheckout();
          }
          if (completed){
            postPaymentFillFunction();
          }
        });
      });
    
    
      var postPaymentFillFunction = function() { 
          payment.resetLoadWaiting();
          
          if (OneId.automateFormFill) {
            // If we're auto form filling, need to show all the other accordian pieces.
            payment.onSave = function(t){
                payment.nextStep(t);
                OneId.$("#oneid-checkout-please-wait").hide();
                OneId.$("#opc-login").addClass("allow").show();
                OneId.$("#opc-billing").addClass("allow").show();
                OneId.$("#opc-shipping").addClass("allow").show();
                OneId.$("#opc-payment").addClass("allow").show();
            }
          }
          
          if (OneId.$("#ccsave_cc_cid,#authorizenet_cc_cid").length){
             OneId.$("#oneid-checkout-please-wait").hide();
             OneId.$("#opc-login").addClass("allow").show();
             OneId.$("#opc-billing").addClass("allow").show();
             OneId.$("#opc-shipping").addClass("allow").show();
             OneId.$("#opc-payment").addClass("allow").show();
             // We don't autofill the CVV, so lets focus on it
             OneId.$("#ccsave_cc_cid").focus();
          }
          else{
            payment.save();
          }
          
      };
      
      var startPaymentsFormFill = function(){
          var attr = "<?php echo $this->helper('OneID')->getCheckoutAttr() ?>";
          paymentPostData.additional_attrs = attr;
          OneIdForm.fill(paymentPostData);
      }
      
      var paymentMissingFields = function(missing_fields) {
          $("opc-payment").show();
          $("checkout-step-payment").show();
       }
      
       var paymentPostData = { 
	"profile" : "checkout",
	"templateId" : "",
        "missingFieldsFunction" : "paymentMissingFields",
	"formData" : {
                "ccsave_cc_owner" : {
			"oneid_attribute" : "payment[cc_name_on_card]",
			"oneid_class" : "",
			"scope" : "oneID",
			"format" : ""
                  },
                  "ccsave_cc_type" : {
			"oneid_attribute" : "payment[cc_type]", 
			"oneid_class" : "",
			"scope" : "oneID",
			"format" : ""
                  },
                  "ccsave_cc_number" : {
			"oneid_attribute" : "payment[cc_number]", 
			"oneid_class" : "",
			"scope" : "oneID",
			"format" : ""
                  },
                  "ccsave_expiration" : {
			"oneid_attribute" : "payment[cc_exp_mo]", 
			"oneid_class" : "",
			"scope" : "oneID",
			"format" : ""
                  },
                  "ccsave_expiration_yr" : {
			"oneid_attribute" : "payment[cc_exp_yr]", 
			"oneid_class" : "",
			"scope" : "oneID",
			"selector_type" : "base",
			"format" : ""
                  }
          }
        };  
        
        
</script>

<div id="one-id-form-payment" class="one-id-form"></div>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close"><img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" title="<?php echo $this->__('Close') ?>" /></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<?php echo $this->getChildChildHtml('additional') ?>
<div class="buttons-set" id="payment-buttons-container">
    <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="button" class="button" onclick="payment.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <div name="AutoFill with OneID" class="oneid-only oneid-formfill-payment" style="float:right; margin-top:-7px; margin-right:5px;">
      
    </div>
<!--    <div name="AutoFill with OneID" class="oneid-only" type="button" style="float:right;">
        <img class="oneid-button" src="<?php echo $this->helper('OneID')->getAccuFillButtonSrc() ?>" onClick="startPaymentsFormFill()" />
    </div>-->
    
    <span id="payment-please-wait" class="please-wait" style="display:none">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>
<p class="required"><?php echo $this->__('* Required Fields') ?></p>
<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-515)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
