<?php $_order = $this->getParentBlock()->getOrder(); ?>  
<div id="getAOneId" style="display: none" class="oneid-successpage-block">
  <p>Make ordering here again easy! Click to sign up for OneID</p>
  <p>  
    <div class="create_oneid_ctr"></div>
  </p>
</div>
<script type="text/javascript">
  OneIdExtern.registerApiReadyFunction(function(){
    OneId.isUserLoggedIn(function(loggedIn){
      if (!loggedIn){
          var data = OneIdUtil.parseJSON('<?php echo $this->helper('OneID')->getCreateOneIdAttrsFromOrder($_order) ?>');
          var challenge = <?php echo $this->helper("OneID")->getLoginCHALJ() ?>;
          OneId.createOneIdButton(".create_oneid_ctr", data, challenge, function(success){
              if (success){
                  // Hide the mssage, now that the user has created a OneID.
                  OneId.$("#getAOneId").hide();
              }
          });
          OneId.$("#getAOneId").show();
        }
      });
  });
</script>
