<?php
$args = Mage::app()->getRequest()->getParams();
$_quote = Mage::getModel('checkout/cart')->getQuote();
?>

<span class="please-wait" id="oneid-checkout-please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('OneID is filling out your form...') ?>" title="<?php echo $this->__('OneID is filling out your form...') ?>" class="v-middle" /> <?php echo $this->__('OneID is filling out your form...') ?>
</span>

<script type="text/javascript">
    var automateFormFill = <?php 
        if (array_key_exists("autoFill", $args)){
            echo 1;
        } 
        else { 
            echo 0;
        } 
        ?>;
    
        var recoverFromFailedOneidCheckout = function(){
            OneId.$("#opc-login").show().addClass("allow");
            OneId.$("#opc-billing").show().addClass("allow");
            OneId.$("#opc-shipping").show().addClass("allow");
            OneId.$("#opc-payment").show().addClass("allow");
            OneId.$("#opc-shipping_method").show().addClass("allow");
            
            OneId.$("#oneid-checkout-please-wait").hide();
            OneId.$("#login\\:guest").click();
            OneId.$("#p_method_ccsave").click();

            OneId.$("#register-xcustomer-password").show();
            OneId.$("#billing\\:customer_password").removeClass("required-entry");
            OneId.$("#billing\\:confirm_password").removeClass("required-entry");          
            OneId.$("#checkout-step-review").hide();
        }
    
    // page level variables.
    var oneIDSaveAttributes = function() {
            var data = {};
            // Elements that were missing from oneID will have this CSS class attached.
            var missing_fields = $$(".oneid-attr-missing");
        
        
            if (missing_fields.length) {
                for (var i=0; i < missing_fields.length; i++) {
                    var missing_field = missing_fields[i];
                    var oneidAttr = null;
                    var missing_field_id = missing_field.id;
                    // Need to go through the JSON blobs defining the forms to get
                    // the form_id -> oneid_attribute mapping.
                    if (billingAddressPostData["formData"][missing_field_id]) {
                        oneidAttr = billingAddressPostData["formData"][missing_field_id]["oneid_attribute"];  
                    }
                    else if (typeof shippingAddressPostData != "undefined" && shippingAddressPostData["formData"][missing_field_id]){
                        oneidAttr = shippingAddressPostData["formData"][missing_field_id]["oneid_attribute"];  
                    }
                    else if (typeof paymentPostData != "undefined" && paymentPostData["formData"][missing_field_id]) {
                        oneidAttr = paymentPostData["formData"][missing_field_id]["oneid_attribute"];
                    }
                
                    if (oneidAttr) {
                        data[oneidAttr] = missing_field.value;
                    }
                
                }
            
                // Call the external setuserattributes, which proxies to server.
                OneId.setUserAttributes(data, function(status){
                    oneidAuthorizePurchase(); 
                });
            }
            else {
                oneidAuthorizePurchase(); 
            }
        };
        var oneidAuthorizePurchase = function() {
            OneId.isUserLoggedIn(function(isLoggedIn){
                if (isLoggedIn){
                    OneId.authSecuredTransaction({'auth_message' : '<?php echo Mage::helper("OneID")->getAuthPurchaseMessage($_quote) ?>',
                        'amount' : '<?php echo $_quote->getGrandTotal() ?>',
                        'challenge' : <?php echo Mage::helper("OneID")->getChalj('secureTransaction', $_quote) ?>
                    }, 
                    function(data) {
                        if (!data) {
                            return;
                        }
                        if (!OneId.$("#oneIdPurchaseAuthData").length){
                            OneId.$('<input id="oneIDPurchaseAuthData" type="hidden" name="oneIDPurchaseAuthData" />').appendTo("#co-payment-form");
                        }
                        
                        
                        $("oneIDPurchaseAuthData").value = OneIdJSON.stringify(data);
                        review.save();
                    });
                }
            
                else{
                    review.save();
                }
            });
        };
        
        var paymentPostData = { 
            "formData" : {
                "[name='payment[cc_owner]']" : {
                    "oneid_attribute" : "payment[cc_name_on_card]",
                    "oneid_class" : "",
                    "scope" : "oneID",
                    "selector_type" : "css"
                },
                "[name='payment[cc_type]']" : {
                    "oneid_attribute" : "payment[cc_type]", 
                    "oneid_class" : "",
                    "scope" : "oneID",
                    "selector_type" : "css"
                },
                "[name='payment[cc_number]']" : {
                    "oneid_attribute" : "payment[cc_number]", 
                    "oneid_class" : "",
                    "scope" : "oneID",
                    "selector_type" : "css"
                },
                "[name='payment[cc_exp_month]']" : {
                    "oneid_attribute" : "payment[cc_exp_mo]", 
                    "oneid_class" : "",
                    "scope" : "oneID",
                    "selector_type" : "css"
                },
                "[name='payment[cc_exp_year]']" : {
                    "oneid_attribute" : "payment[cc_exp_yr]", 
                    "oneid_class" : "",
                    "scope" : "oneID",
                    "selector_type" : "css"
                }
            }
        }; 
        
        var billingAddressPostData = { 
            "formData" : {
                "billing:firstname" : {
                    "oneid_attribute" : ["personal_info[first_name]"]
                },
                "billing:lastname" : {
                    "oneid_attribute" : ["personal_info[last_name]"]
                  
                },
                "billing:email" :{
                    "oneid_attribute" : ["personal_info[email]"]
                },
                "billing:street1" :{
                    "oneid_attribute" : "address[billing][street]" 
                },
                "billing:street2" :{
                    "oneid_attribute" : "address[billing][street2]", 
                    "required" : false
                },
                "billing:telephone" :{
                    "oneid_attribute" : "address[billing][phone]" 
                },
                "billing:region_id" :{
                    "oneid_attribute" : "address[billing][state]"
                },
                "billing:city" : {
                    "oneid_attribute" : "address[billing][city]" 
                },
                "billing:postcode" : {
                    "oneid_attribute" : "address[billing][zip]" 
                }
            }
        };
        
        var shippingAddressPostData = { 
            "formData" : {
                "shipping:firstname" : {
                    "oneid_attribute" : "personal_info[first_name]"
                },
                "shipping:lastname" : {
                    "oneid_attribute" : "personal_info[last_name]"
                },
                "shipping:street1" :{
                    "oneid_attribute" : "address[shipping][street]" 
                },
                "shipping:street2" :{
                    "oneid_attribute" : "address[shipping][street2]",
                    "required": false
                },
                "shipping:telephone" :{
                    "oneid_attribute" : "address[shipping][phone]"
                },
                "shipping:region_id" :{
                    "oneid_attribute" : "address[shipping][state]"
                },
                "shipping:city" : {
                    "oneid_attribute" : "address[shipping][city]"
                },
                "shipping:postcode" : {
                    "oneid_attribute" : "address[shipping][zip]"
                }
            }
        }; 
    
    
    OneIdExtern.registerApiReadyFunction(function(){
        // insert buttons
        var loginCtr = '<div class="oneid-only oneid-checkout-signin-container" style="margin-top:25px;"><div id="oneid-checkout-login-form" class="oneid-only oneid-login-container" style="" ></div></div>';
        OneId.$(loginCtr).insertAfter("#checkout-step-login .col-2 .buttons-set .button");
        
        // billing
        var billingCtr = '<div name="AutoFill with OneID" class="oneid-only oneid-formfill-billing" style="float:right;"></div>';
        OneId.$(billingCtr).insertAfter("#co-billing-form .button");
        
                // billing
        var shippingCtr = '<div name="AutoFill with OneID" class="oneid-only oneid-formfill-shipping" style="float:right;"></div>';
        OneId.$(shippingCtr).insertAfter("#co-shipping-form .button");
        
        //payment
        var paymentCtr = '<div name="AutoFill with OneID" class="oneid-only oneid-formfill-payment" style="float:right;"></div>'
        OneId.$(paymentCtr).insertAfter("#checkout-step-payment .button");
        

        
        // attach the OneId login button
        OneId.loginButton(OneId.$("#oneid-checkout-login-form"), { "challenge" : <?php echo $this->helper("OneID")->getCheckoutLoginCHALJ() ?> });
        
            
        var postPaymentFillFunction = function() { 
            payment.resetLoadWaiting();
          
          
            if (OneId.$("#ccsave_cc_cid,#authorizenet_cc_cid").length){
                OneId.$("#oneid-checkout-please-wait").hide();
                OneId.$("#opc-login").addClass("allow").show();
                OneId.$("#opc-billing").addClass("allow").show();
                OneId.$("#opc-shipping").addClass("allow").show();
                OneId.$("#opc-payment").addClass("allow").show();
                // We don't autofill the CVV, so lets focus on it
                OneId.$("#ccsave_cc_cid").focus();
            }
            else{
                payment.save();
            }
          
        };
      
        var startPaymentsFormFill = function(){
            var attr = "<?php echo $this->helper('OneID')->getCheckoutAttr() ?>";
            paymentPostData.additional_attrs = attr;
            OneIdForm.fill(paymentPostData);
        }
      
        var paymentMissingFields = function(missing_fields) {
            $("opc-payment").show();
            $("checkout-step-payment").show();
        }
      
 
        
        OneId.accuFillButton(OneId.$(".oneid-formfill-payment"), paymentPostData, "", function(completed){
            if (!completed && automateFormFill){
                recoverFromFailedOneidCheckout();
            }
            if (completed){
                postPaymentFillFunction();
            }
        });
  
        var billingAddressFillSuccess = function() { 
            
            if (automateFormFill){
                billing._onSave = billing.onSave;                     
                billing.onSave = function(t){
                    var data = {};
                    try{
                        data = OneIdUtil.parseJSON(t.responseText);
                        if (window.shipping){
                            if (data.goto_section == "shipping_method"){
                                if (data.update_section) {
                                    $('checkout-'+data.update_section.name+'-load').update(data.update_section.html);
                                    OneId.$("[name='shipping_method']").first().attr("checked", "checked");
                                }
                                delete data['update_section'];
                                delete data['goto_section'];
                                t.responseText = OneIdUtil.stringifyJSON(data);
                            }
                            billing._onSave(t);
                            
                            checkout.loadWaiting=false;
                            shippingMethod.save();
                        }
                        else{
                            recoverFromFailedOneidCheckout();
                            var filledOut = isFormFilledOut(paymentPostData.formData);
                            if (filledOut){  
                                checkout.loadWaiting = false;
                                payment.save();
                            }
                            else{
                                checkout.gotoSection("payment");
                            }
                        }
                    }
                    catch(e){

                    }
                }
                
            }
            
            OneId.$("#p_method_ccsave").click();
            OneId.$("#payment_form_ccsave").show();
            billing.save();
//
//            if (OneId.$("#opc-shipping_methods").length){
//                recoverFromFailedOneidCheckout();
//            }  
            
        };
      
        function escapeSelector(str){
            if( str){
                return str.replace(/([ #;&,.+*~\':"!^$[\]()=>|\/@])/g,'\\$1')
            }
            else  {
                return str;
            }
        }
      
        var isFormFilledOut = function(formData){
            for(key in formData){
                var selector = OneId.$("#"+escapeSelector(key));
                if (typeof formData[key].required == "undefined" || formData[key].required == true){
                    if (selector.length && !selector.val()){
                        return false;
                    }
                }
            }
            
            return true;
        };
      
        // Need this function for auto-filling.
        var startBillingAddressFormFill = function() {
            var attr = "<?php echo $this->helper('OneID')->getCheckoutAttr() ?>";
        
            billingAddressPostData.additional_attrs = attr;
        
            OneIdForm.fill(billingAddressPostData, "", false, function(completed){
                
                var filledOut = isFormFilledOut(billingAddressPostData.formData);
                
                if (automateFormFill && (!completed || !filledOut)){
                    recoverFromFailedOneidCheckout();
                    checkout.gotoSection("billing");
                }
                else {
                    if (completed){
                        billingAddressFillSuccess();
                    }
                }
            });
        }
      

      
        var billingAddressMissingFields = function(missing_fields) {
            if (automateFormFill){
                recoverFromFailedOneidCheckout();
            }
            checkout.gotoSection("billing");
            $("opc-billing").show();
          
        };
    

        
        var oneidBillingNextStep = function() {
            OneId.isUserEnabled( function (isEnabled) {
                if (isEnabled) {
                    billingAddressFillSuccess();
                    $("opc-payment").show();
                }
                else {
                    billing.save();
                }
            });
        };
        
        OneId.accuFillButton(OneId.$(".oneid-formfill-billing"), billingAddressPostData, "", function(completed){
            if (!completed && automateFormFill){
                recoverFromFailedOneidCheckout();
            }
            if (completed){
                billingAddressFillSuccess();
            }
        });
        


        //<!-- shipping.phtml -->

        var postShippingAddressFunction = function() { 
            shipping.save(); 
           
            if (automateFormFill) {
                
                OneId.$("#opc-shipping_methods").show();
                
                
                }
        };
       
        var shippingAddressMissingFields = function(missing_fields) {
            if (automateFormFill){
                recoverFromFailedOneidCheckout();
            }
            checkout.gotoSection("shipping");
            $("opc-shipping").show();
        }
       
 
        
        var startShippingAddressFormFill = function() {
            var attr = "<?php echo $this->helper('OneID')->getCheckoutAttr() ?>";
            OneIdForm.fill(shippingAddressPostData);
        };
        

        OneId.accuFillButton(OneId.$(".oneid-formfill-shipping"), shippingAddressPostData, "", function(completed){
            if (!completed && automateFormFill){
                recoverFromFailedOneidCheckout();
            }
            if (completed){
                postShippingAddressFunction();
            }
        });

        OneId.isUserEnabled(function(isEnabled){
            if (isEnabled){
                OneId.$(".oneid-only").show();
                
                if (automateFormFill){
                    OneId.$("#opc-login").hide();
                    OneId.$("#opc-billing").hide();
                    OneId.$("#opc-shipping").hide();
                    OneId.$("#opc-shipping_method").hide();
                    OneId.$("#opc-payment").hide();
                    OneId.$("#oneid-checkout-please-wait").show();


                    OneId.$("#login\\:guest").click();
                    OneId.$("#p_method_ccsave").click();
                    OneId.$("#p_method_authorizenet").click();
                    OneId.$("#billing\\:use_for_shipping_yes").click();

                    OneId.$("#register-xcustomer-password").hide();
                    OneId.$("#billing\\:customer_password").removeClass("required-entry");
                    OneId.$("#billing\\:confirm_password").removeClass("required-entry");          
                    OneId.$("#checkout-step-review").show();
                    
                    if (typeof shippingMethod != "undefined"){
                        shippingMethod.onSave = function(transport){
                            if (transport && transport.responseText){
                                try{
                                    response = eval('(' + transport.responseText + ')');
                                }
                                catch (e) {
                                    response = {};
                                }
                            }

                            if (response.error) {
                                alert(response.message);
                                return false;
                            }

                            payment.initWhatIsCvvListeners();

                            if (response.payment_methods_html) {
                                $('checkout-payment-method-load').update(response.payment_methods_html);
                            }
                            recoverFromFailedOneidCheckout();
                            if (isFormFilledOut(paymentPostData.formData) && !OneId.$("#ccsave_cc_cid,#authorizenet_cc_cid").length){
                                checkout.loadWaiting=false;
                                payment.save();   
                            }
                            else{
                                checkout.setShippingMethod();
                            }
                            
                        }
                    }
                    
                    var autoFillFormData = OneId.$.extend({}, billingAddressPostData.formData, paymentPostData.formData);
                    var autoFillMap = {
                        "formData" : autoFillFormData
                    };
                    
                    OneIdForm.fill(autoFillMap, "", false, function(completed){
                        
                        var filledOut = isFormFilledOut(billingAddressPostData.formData);
                        if (automateFormFill && (!completed || !filledOut)){
                            recoverFromFailedOneidCheckout();
                            checkout.gotoSection("billing");
                        }
                        else {
                            if (completed){             
                                billingAddressFillSuccess();
                            }
                        }
                    });
                   
                }
            }
        });
      
        
    });
</script>